### ISSUE TITLE
issue with saving (CueIDs)

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBDMOrganizer#1]
YaBDMOrganizer v0.1.1

When opening the BDM, in the "Sound" tab, it shows Sound IDs as "0" in the text box (while it might be -1 in the BDM)

this is due to the textbox not expecting a negative input, which does the affect the BDM when saving (CueID will be saved as 0 instead of -1)

**Comment by KyonkoYuuki** [comment]
Fixed
