### ISSUE TITLE
Add more damage types

### ISSUE THREAD

**Issue by UnleashedGH** [KyonkoYuuki/YaBDMOrganizer#4]
**1470_TPO_BVA_PLAYER.bdm** has damage type 29, but YaBDM damage types stop at 27
and such this error message appears 
![image](https://user-images.githubusercontent.com/47185022/83461963-a7ffaf00-a472-11ea-92c2-8f204d7807e7.png)

**Comment by KyonkoYuuki** [comment]
update this then, then I'll add it in.
https://docs.google.com/document/d/18gaAbNCeJyTgizz5IvvXzjWcH9K5Q1wvUHTeWnp8M-E/edit#heading=h.irjxly77aguh

**Comment by KyonkoYuuki** [comment]
Updated to show unknown.  Open a new issue whenever you figure out what that is.
